### ISSUE TITLE
Strip link extensions

### ISSUE THREAD

**Issue by wqweto** [Detry322/redisred#7]
Make `https://redisred.herokuapp.com/hello.png` equivalent to `https://redisred.herokuapp.com/hello` if target `hellog.png` is not registered already (i.e. strip "file" extension).

This allows forums which filter on valid sources for [img] tags being png/gif/jpg static files to be fooled to redirect to svg or any dynamic content (github badges?).

`http://ow.ly` does it.

**Comment by Detry322** [comment]
I guess I don't understand fully - if `hello.png` isn't registered, why can't you just manually redirect `hello.png` to `/hello` (if you don't supply a `http://` it redirects to the relative path). Then, you can make the `hello` redirect whatever you want

**Comment by wqweto** [comment]
Oops, my bad. I though keys were sanitized (as all other redirectors do).

Will close this now.
